version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - db-data:/var/lib/mysql
      - ./db-data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
  web:
    image: wordpress
    build: .
    volumes:
      - ./themes:/var/www/html/wp-content/themes
    links:
      - db
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
volumes:
  db-data:
    driver: local
